language:
  - node_js

node_js:
    - '10'

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:

script:
  - npm run build
  - npm run generate
# E: Build LifeCycle

branches:
  only:
    - master